/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoinRouteImport } from './routes/join'
import { Route as TabsRouteImport } from './routes/_tabs'
import { Route as TabsIndexRouteImport } from './routes/_tabs.index'
import { Route as UsersUserIdRouteImport } from './routes/users.$userId'
import { Route as RoomsOpenRouteImport } from './routes/rooms.open'
import { Route as RoomsNewRouteImport } from './routes/rooms.new'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms.$roomId'
import { Route as TabsProfileRouteImport } from './routes/_tabs.profile'
import { Route as RoomsRoomIdMembersRouteImport } from './routes/rooms.$roomId_.members'
import { Route as RoomsRoomIdEditRouteImport } from './routes/rooms.$roomId_.edit'

const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsRoute = TabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsIndexRoute = TabsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TabsRoute,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsOpenRoute = RoomsOpenRouteImport.update({
  id: '/rooms/open',
  path: '/rooms/open',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsNewRoute = RoomsNewRouteImport.update({
  id: '/rooms/new',
  path: '/rooms/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsProfileRoute = TabsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TabsRoute,
} as any)
const RoomsRoomIdMembersRoute = RoomsRoomIdMembersRouteImport.update({
  id: '/rooms/$roomId_/members',
  path: '/rooms/$roomId/members',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdEditRoute = RoomsRoomIdEditRouteImport.update({
  id: '/rooms/$roomId_/edit',
  path: '/rooms/$roomId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof TabsIndexRoute
  '/join': typeof JoinRoute
  '/profile': typeof TabsProfileRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/rooms/new': typeof RoomsNewRoute
  '/rooms/open': typeof RoomsOpenRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/rooms/$roomId/edit': typeof RoomsRoomIdEditRoute
  '/rooms/$roomId/members': typeof RoomsRoomIdMembersRoute
}
export interface FileRoutesByTo {
  '/join': typeof JoinRoute
  '/profile': typeof TabsProfileRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/rooms/new': typeof RoomsNewRoute
  '/rooms/open': typeof RoomsOpenRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/': typeof TabsIndexRoute
  '/rooms/$roomId/edit': typeof RoomsRoomIdEditRoute
  '/rooms/$roomId/members': typeof RoomsRoomIdMembersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_tabs': typeof TabsRouteWithChildren
  '/join': typeof JoinRoute
  '/_tabs/profile': typeof TabsProfileRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/rooms/new': typeof RoomsNewRoute
  '/rooms/open': typeof RoomsOpenRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/_tabs/': typeof TabsIndexRoute
  '/rooms/$roomId_/edit': typeof RoomsRoomIdEditRoute
  '/rooms/$roomId_/members': typeof RoomsRoomIdMembersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join'
    | '/profile'
    | '/rooms/$roomId'
    | '/rooms/new'
    | '/rooms/open'
    | '/users/$userId'
    | '/rooms/$roomId/edit'
    | '/rooms/$roomId/members'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/join'
    | '/profile'
    | '/rooms/$roomId'
    | '/rooms/new'
    | '/rooms/open'
    | '/users/$userId'
    | '/'
    | '/rooms/$roomId/edit'
    | '/rooms/$roomId/members'
  id:
    | '__root__'
    | '/_tabs'
    | '/join'
    | '/_tabs/profile'
    | '/rooms/$roomId'
    | '/rooms/new'
    | '/rooms/open'
    | '/users/$userId'
    | '/_tabs/'
    | '/rooms/$roomId_/edit'
    | '/rooms/$roomId_/members'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TabsRoute: typeof TabsRouteWithChildren
  JoinRoute: typeof JoinRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
  RoomsNewRoute: typeof RoomsNewRoute
  RoomsOpenRoute: typeof RoomsOpenRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
  RoomsRoomIdEditRoute: typeof RoomsRoomIdEditRoute
  RoomsRoomIdMembersRoute: typeof RoomsRoomIdMembersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/': {
      id: '/_tabs/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof TabsIndexRouteImport
      parentRoute: typeof TabsRoute
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/open': {
      id: '/rooms/open'
      path: '/rooms/open'
      fullPath: '/rooms/open'
      preLoaderRoute: typeof RoomsOpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/new': {
      id: '/rooms/new'
      path: '/rooms/new'
      fullPath: '/rooms/new'
      preLoaderRoute: typeof RoomsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/profile': {
      id: '/_tabs/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof TabsProfileRouteImport
      parentRoute: typeof TabsRoute
    }
    '/rooms/$roomId_/members': {
      id: '/rooms/$roomId_/members'
      path: '/rooms/$roomId/members'
      fullPath: '/rooms/$roomId/members'
      preLoaderRoute: typeof RoomsRoomIdMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId_/edit': {
      id: '/rooms/$roomId_/edit'
      path: '/rooms/$roomId/edit'
      fullPath: '/rooms/$roomId/edit'
      preLoaderRoute: typeof RoomsRoomIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TabsRouteChildren {
  TabsProfileRoute: typeof TabsProfileRoute
  TabsIndexRoute: typeof TabsIndexRoute
}

const TabsRouteChildren: TabsRouteChildren = {
  TabsProfileRoute: TabsProfileRoute,
  TabsIndexRoute: TabsIndexRoute,
}

const TabsRouteWithChildren = TabsRoute._addFileChildren(TabsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  TabsRoute: TabsRouteWithChildren,
  JoinRoute: JoinRoute,
  RoomsRoomIdRoute: RoomsRoomIdRoute,
  RoomsNewRoute: RoomsNewRoute,
  RoomsOpenRoute: RoomsOpenRoute,
  UsersUserIdRoute: UsersUserIdRoute,
  RoomsRoomIdEditRoute: RoomsRoomIdEditRoute,
  RoomsRoomIdMembersRoute: RoomsRoomIdMembersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
